name = "DejaVu"
uuid = "7cbc2c3e-f684-4893-ab98-7f2d54138155"
authors = ["Resul Akay <akay.86@hotmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
